### ISSUE TITLE
Change the terminal ouput to be platform independent when creating an ssh key

### ISSUE THREAD

**Issue by astroDimitrios** [swcarpentry/git-novice#1046]
### How could the content be improved?

For instance in 3.1 the first output block shows:

```bash
Generating public/private ed25519 key pair.
Enter file in which to save the key (/c/Users/Alfredo/.ssh/id_ed25519):
```

we suggest changing the path to:

```bash
Enter file in which to save the key (~/.ssh/id_ed25519):
```

in all instances where there are `/c/Users/Alfredo/` in the lesson episode.

### Which part of the content does your suggestion apply to?

https://www.astropython.com/git-novice/07-github.html#create-an-ssh-key-pair

**Comment by martinosorb** [comment]
Hi Dimitrios, I tried on my Linux laptop and I get
```bash
Generating public/private ed25519 key pair.
Enter file in which to save the key (/home/martino/.ssh/id_ed25519): 
```
so it seems to me that no platform actually answers the command in the way you suggest. The text in the lesson reflects the way `ssh-keygen` behaves. Later in the lesson, the command 
```bash
cat ~/.ssh/id_ed25519.pub```
correctly uses the `~` notation in order to be platform independent, but it's in a place where we can actually decide what notation to use.
