### ISSUE TITLE
Should we teach interactive mode?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#187]
http://git-scm.com/book/ch7-2.html

**Comment by wking** [comment]
On Sat, Nov 14, 2015 at 11:45:44PM -0800, Greg Wilson wrote:
> http://git-scm.com/book/ch7-2.html

I vote “no”.

Discovering what you need to change is often a messy process, and I
use ‘git add -p’ all the time to stage an atomic, focused commit from
a working directory filled with debugging code and unrelated changes.
But I think we have enough going on in the novice Git lesson teaching
the basic mechanics.  The finer points about crafting a *good* commit
are less important than being able to make a commit at all or managing
remotes and push/pull collaboration.  I'd prioritize branches, pull
requests, and explicit merges over commit construction, since it's a
lot easier to motivate focused, well-motivated commits when you are
explicitly talking about suggesting changes (the current lesson only
gets as far as reacting to conflicts).  And if you're not focusing on
crafting an atomic commit, the blunt “git commit -a …”, “git add …”,
etc. are all good enough.

**Comment by daisieh** [comment]
@gvwilson, it seems like you have a lot of ideas that would be excellent fodder for a git-intermediate lesson! As it is, we can usually barely get to forking and pull requests in the workshops.
