### ISSUE TITLE
Get Git working behind firewalls

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#224]
See https://github.com/swcarpentry/bc/issues/744

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 08:13:37AM -0800, Greg Wilson wrote:
> See https://github.com/swcarpentry/bc/issues/744

The original issue started off talking about institutional firewalls:

  {WAN} -- {firewall} -- {LAN} -- {instructor}
                             `-- {learner}

For example, “the Federal Reserve blocks access to GitHub / the whole
WAN” or “network infrastructure in our city/country/instution isn't
reliable, so we may not have access to GitHub”.

But there was also some discussion of *user* firewalls [1]:

  {LAN} -- {instructor}
      `-- {firewall} -- {learner}

The latter is only likely to be a problem if you try the ‘git daemon’
route, but there aren't all that many alternatives for teaching
collaborative Git when the WAN isn't accessible.  @chendaniely was
using a network filesystem, but that relies on the isolated LAN having
a network filesystem already setup (because setting up a network
filesystem from scratch is going to be more work than setting up ‘git
daemon’ from scratch ;).

And the lowest-common-denominator approach is giving up on actual
collaboration and just having folks fake collaboration by using
multiple directories on their own box and having each learner put on
two hats and collaborate with themselves.  At that point, I think
we're tiptoeing close to “to confusing to be getting much information
across to new users”.  But we may be able to squeeze some knowledge
through if the learners are already comfortable with novice Git.

[1]: https://github.com/swcarpentry/bc/issues/744#issuecomment-56869942

**Comment by gvwilson** [comment]
Hm - instructor's guide?

**Comment by chendaniely** [comment]
The only time I've found this to be problematic was the workshop at the Federal Reserve.

Not sure how the CDC workshop recently worked out.

I'd like to think that places that have firewall restrictions may have their own internal Git server (e.g, GItLab) so this may or may not be an issue.
However, I'm not sure what an alternative would be if GitLab is not set up.... Teach them about branches and merging (sounds like a bad idea)?

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 10:34:19AM -0800, Daniel Chen wrote:
> The only time I've found this to be problematic was the workshop at
> the Federal Reserve.

Also recently resurfaced on discuss@ [1], the Kenya DC workshop had
GitHub issues (among other things) due to flaky internet [2].

> I'd like to think that places that have firewall restrictions may
> have their own internal Git server (e.g, GitLab) so this may or may
> not be an issue.

Ah, that would be nice :).

> However, I'm not sure what an alternative would be if GitLab is not
> set up.... Teach them about branches and merging (sounds like a bad
> idea)?

I feel like if we're comfortable teaching merging and conflicts (which
we do in this repo's topic 9), then we're already teaching them about
branching ;).  But yeah, for novices I expect explicit branching falls
under the same “one person, many hats” confusion that makes using two
directories on the same box difficult [3].

[1]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2016-February/003818.html
     Subject: [Discuss] SWC connections in Kenya
     Date: Tue, 2 Feb 2016 13:50:35 -0500
     Message-ID: <56B0FA7B.4000302@weecology.org>
[2]: http://www.datacarpentry.org/blog/tdwg/
[3]: https://github.com/swcarpentry/git-novice/issues/224#issuecomment-179366422

**Comment by wking** [comment]
On Wed, Feb 03, 2016 at 10:25:29AM -0800, Greg Wilson wrote:
> Hm - instructor's guide?

I think it may be more complicated an issue than we want to cover in
an instructors.md issue.  ‘git grep -i github *.md’ only turns up
meaningful hits in 07-github, 08-collab, and 09-conflict.  I'd rather
provide an alternate track (07-b-git-daemon.md, etc.?), but I don't
mind if that lives in this repo or in another repo
(git-novice-git-daemon?) that periodically pulls from this lesson and
just replaces the GitHub topics with alternatives.  I'm happy to help
maintain either if they sound appealing (I don't expect much churn in
the ‘git daemon’ workflow).

**Comment by nathanhruby** [comment]
Would a precanned docker or vagrant image with GitLab or other suitable central git server that instructors could fire up at isolated teaching site be useful in addressing this issue?

It doesn't address the issue of being able to view your work later, but it does solve the issue of "doing things with a remote."

**Comment by iglpdc** [comment]
Hi, @nathanhruby. Maybe... We could add instructions to the instructor's guide on how to do it. However, I think it still would be complicated to set up for the average instructor. You not only have to set up the docker container, but you also have to configure your laptop to allow connections on some ports.

I'm not a expert, but if you think that it can be set up more or less easily, it would definitely by a good addition.

Would you like to submit a PR with your solution?
