### ISSUE TITLE
Add back in pictures of Wolfman and Dracula

### ISSUE THREAD

**Issue by abostroem** [swcarpentry/git-novice#23]
The SVN version of this lesson included pictures of Wolfman and Dracula. It would be nice to have this pictures made relevant for git and added into the lesson.

**Comment by r-gaia-cs** [comment]
The pictures of Wolfman and Dracula are stored at the `*.ppt` files available at https://github.com/swcarpentry/v4/tree/master/vc. I don't know of one tool that can extract the pictures.

**I tried use `pdftohtml` with the `*.pdf` but for some reason it split the pictures in two parts.**

**Comment by abought** [comment]
> I don't know of one tool that can extract the pictures.

Fun fact: all modern powerpoint files (.pptx) are actually .zip archives with a different extension. Export to .pptx, rename to .zip, and for intro.pptx, the media files you want will be `ppt/media/image4.png` and `ppt/media/image5.png`.

Advantage is that you get basically the raw original image with fewer changes from whatever intermediate tool was used.

(I'd upload the images as pull request, but not sure where what folder to deposit them in)

**Comment by jiffyclub** [comment]
Is this really necessary? @abostroem, where on the site were you thinking of adding the figures?

**Comment by gvwilson** [comment]
People do seem to like the pictures... but I only have them as raster, not as vector.  If only we knew someone who was artistically inclined and understood computer-friendly graphics formats and, you know, wanted to get involved in a project that seemed to be eating up a lot of their spouse's free time :-)

**Comment by jiffyclub** [comment]
If we want new art we'll need a good description of what we want. Do we want just portraits of Dracula and Wolfman, or a whole set of them doing stuff?

**Comment by gvwilson** [comment]
The old (hand-drawn) set was one picture each of Dracula, Wolfman, the 
Mummy, and Frankenstein in front of their PCs.  It would be great to 
have simple cartoonish vector art of them all with laptops (Dracula, of 
course, will be wearing sunglasses and sipping a flat white).  Beyond 
that, I dunno - though I *am* fond of art like this:

* https://openclipart.org/detail/167888/green-monster-ns-by-rduris
* https://openclipart.org/detail/167887/red-monster-ns-by-rduris

**Comment by daisieh** [comment]
I would like to know if people are really using these figures in teaching before we figure out if anyone wants to update the figures. Personally, I hate the whole Wolfman/Dracula thing: it is goofy and it doesn't correspond to any way that I've ever used version control, so it seems like goofy cartooning for no particular reason.

**Comment by abostroem** [comment]
@daisieh When I teach collaborating in git I have everyone pair up. I have them choose who is Wolfman and who is Dracula and then throughout the exercise I refer to what Wolfman should be doing and Dracula should be doing. The students seem to like it and it's easier for them to keep their roles straight. (before I was using partner 1 and partner 2 and people would get confused). It is nice to have a visual picture of them. My only hesitation (which I'm still debating internally) is whether we should make one of them female.

**Comment by daisieh** [comment]
Hm. When @ttimbers and I role-played, we had two people be "collaborator" and "owner" of the repo, which serves the same purpose?

**Comment by iglpdc** [comment]
I agree with @abostroem. I failed every time I tried to do partner 1/2 or owner/collaborator. Also, one important thing to consider is that sometimes there is only one instructor doing both roles (say the projector or room doesn't make easy to have two people on stage at once.)

Note, however, that the current lesson doesn't teach PRs, but just adding a collaborator. For that the role play is much more easy and, in fact, the lesson mentions only a "vlad", not Dracula or Wolfman. Some instructors teach how to collaborate by PRs, instead of just adding a collaborator - I do if I have time -, so characters for role play would be nice.

I'd like to get a decision on this at some point. Some proposals are:

1. close this issue without adding the pics,
2. remake `06-collab.md` to explicitly use Dracula and Wolfman, instead of owner and collaborator, (this could add the pics or not)
3. make a script for role playing, with Dracula and Wolfman. The script would consist of the commands each role has to enter, would be a separate file that instructors handout/follow during role playing and, importantly, will clearly mark who is entering what, so chances of messing up are greatly reduced. 
4. Additionally, we should consider adding a female character, although this breaks the history of the lesson. Any suggestions, @abostroem?

I'm +1 for 2,3, and +0.5 for 4 (+1 for gender, -0.5 for breaking the history.) 

What do you think?

**Comment by amueller** [comment]
Reading through the lessons, I am somewhat stumped by the wolfman and dracula thing.
It has a very different tone than the start of the other tutorials.

First sentence in git:
> Wolfman and Dracula have been hired by Universal Missions (a space services spinoff from Euphoric State University) to investigate if it is possible to send their next planetary lander to Mars. 

first sentence in make:
> Make is a tool which can run commands to read files, process these files in some way, and write out the processed files. 

first sentence in mercurial:
> Version control is the lab notebook of the digital world: it’s what professionals use to keep track of what they’ve done and to collaborate with other people. 

Scientists are busy. If I read the first sentence telling me a story about fantasy characters, I'm really confused. I think the first sentences should be

> Git does version control. Version control is X.

I'm not against having stories. I just think a lesson should start with an intro, not a story.
And as far as stories go, I feel a more relatable story would catch the attention of the audience more.
I realize this is meant to be light-hearted, but it reads like it's written for children. I prefer nelle nemo.

Also, I'm slightly confused by how different the mecurial and git lessons are. Wouldn't it make more sense for them to be much more synced? Or is this a non-blind test to see which way of teaching works better?

**Comment by abostroem** [comment]
When I teach git I open with What is git and what is version control. When we start creating a file, I find it useful to have a story line. Students can more quickly come up with a file name, everyone's file names are the same (so they can type what I'm typing), and students more quickly come up with sentences to add when they have a directed prompt. So for local version control we work with a file called mars.txt as a class and then they repeat what they have done in exercises on a file called jupiter.txt. The text in both files is about Wolfman or Dracula living on Mars or Jupiter. 
When I teach collaboration using git and github, I divide them into pairs and assign one person to be Dracula and one person to be Wolfman. Directions from this point on are directed at Dracula or at Wolfman. This is memorable enough that they keep straight who they are (and follow the correct set of direction) and is a fun story line for students to follow - it leads to sentences like "ok, now Dracula should clone Wolfman's repository". My lesson outline and exercises can be found in: local: http://slides.com/abostroem/local_version_control and collaboration: http://slides.com/abostroem/deck-5

**Comment by amueller** [comment]
[OT] @abostroem I'm actually preparing to give a course based on http://jiffyclub.github.io/2015-07-06-scipy/ and your presentations, which is why I'm going through everything. They are great!
[/OT]
I don't argue against a story line. I'm just not sure if that is the first thing that should be presented. And you can have memorable names that are not ridiculous.

**Comment by amueller** [comment]
sorry for OT again: @abostroem is there a part in the SWC material that corresponds to your deck about branches? I didn't find that material.

**Comment by iglpdc** [comment]
Thanks for your comments @amueller. I guess the reason we have the story about Dracula and Wolfman is because at some point in history these lessons were a narrated slideshow posted in the Internet. Dracula and Wolfman showed up as cartoons (that's why this issue is claiming them back) to illustrate the slides.

All these years we have been changing most of the materials, but the background story somehow remained. (I'd dare to say that the lesson **predates** Git and remember the original Dracula and Wolfman using SVN as VCS).

While I guess everybody agrees in having a story to backup the lesson, I heard other people preferring/using other stories. I personally don't like that there's a lot to type in each of the commits, so I use a different tale. I don't find the story inappropriate for our workshops, which are very informal, and I've never heard about learners being confused by the story (they usually get confused by the stage or some other Git trick).

If enough people prefer a change, we can open an new issue and pitch alternate stories.

**Comment by iglpdc** [comment]
I'm closing this as not many people is pushing really hard for having the pictures back. From wider point of view, mention your preferences about the background story in #277
