### ISSUE TITLE
Add clarification of working directory to start of Tracking Changes section

### ISSUE THREAD

**Issue by gallington** [swcarpentry/git-novice#283]
In Lesson: Version Control with git
Creating Repository ---> Tracking Changes
--at end of Creating Repository section you create a new dir called moons. It is unclear whether this is to be the new wd for the next step (Tracking Changes) or if it should be moved back to planets. 
Add direction as to which working directory you should be in: planets or moons.
Should moons subdirectory still exist? Or should this be deleted altogether?

**Comment by iglpdc** [comment]
Oh, @gallington, I see your point. It's true that maybe confusing. It'd be very simple to fix adding some text at the beginning the next topic, in the sentence: 

"Let's create a file called `mars.txt` that contains some notes ... ".

Maybe:

 "Let's go back to the planets directory (`$cd ~/Desktop/planets$`) and create a file called `mars.txt` that contains some notes ..."

@gallington, do you wanna send a fix? :)

**Comment by brainwane** [comment]
I think it's a great idea to have a step here where we make sure that the learner is in the correct directory -- do we need to take anything else *out* of this episode to make room for this step? I ask this particularly because the earlier episodes do not use `pwd`, so we're introducing it for the first time here, which may end up taking 30 seconds to a minute of explanation.
