### ISSUE TITLE
Extension Material "Git-Extras"

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry/git-novice#306]
I've submitted a [Pull Request on Branches](https://github.com/swcarpentry/git-novice/pull/303) to add a supplementary lesson, in addition to the RStudio supplement.

It may be more suitable to start a "git-extras" repository for such intermediate level topics, analogous to: https://github.com/swcarpentry/shell-extras

**Comment by iglpdc** [comment]
I think your branch fits better in an intermediate lesson. The difference between extras and intermediate is that extras are things that don't fit in the lesson, mostly for time reasons, are not key for the learning goals of the lesson, but have the same difficulty level as the rest of the lesson (an example could be configuring RStudio+git). Things that are more difficult, as branching, should go on the intermediate lesson.

I prefer to hold the new intermediate materials as open issues/PR in this repo until we move them to the new repo, rather than create a temporary git-extras repo which we will have to redo at some point.

**Comment by TomKellyGenetics** [comment]
Thanks I had no idea we had a "git-intermediate", I agree this would be an ideal place for this content.

Do you mean this repo? This goes a lot deeper into git than what I had in mind. That's ok but it's a different tone to what I've written. I'll submit a PR in case anyone wants to rework it into something more cohesive.

https://github.com/bast/swc-intermediate-git

**Comment by TomKellyGenetics** [comment]
The above repo seems to have been deleted but there is one here: https://rgaiacs.github.io/swc-git-intermediate/04-branches.html
