### ISSUE TITLE
A place to record interesting ways to teach git?

### ISSUE THREAD

**Issue by jangari** [swcarpentry/git-novice#313]
It came up in a lesson debrief that there are a number of ways that people have to teach git to make it more interesting, such as using lego, drawing diagrams, using props like toy monkeys, and so forth. I'm wondering whether there's a resource where we might keep these suggestions to enable less experienced trainers to, you know, stand on others' shoulders.

**Comment by TomKellyGenetics** [comment]
What's wrong with here? GitHub issues seems like the right place to discuss things specific to the git lesson and it's lead to fruitful discussion on related topics:

Comparing to teaching in an IDE: https://github.com/swcarpentry/git-novice/issues/304
Slides: https://github.com/swcarpentry/git-novice/issues/206

However these approaches may not fit within the scope of an SWC workshop (particularly if going into the graph theory) and may be better suited to extension topics such as the Mozilla Study Group model.

**Comment by weaverbel** [comment]
@jangari I use lego to illustrate the revisions going in to a git repo - the lego helps show how each revision is a new file, but that the old file is still there. Lego is also useful when demonstrating HEAD, HEAD ~1 etc. Lots of people use the 'recipe' analogy for Git too - forking a family recipe so that each person's variations can be listed. I think there is a taco recipe repository on GitHub. Also good to highlight Git for hosting blogs, e.g. https://github.com/barryclark/jekyll-now, and how useful raising GitHub issues can be for collaborating.

**Comment by jangari** [comment]
@TomKellyGenetics, yes, here works fine. Thanks for those links!

@weaverbel, thanks for the tips. I love the lego idea and the recipe example.

**Comment by weaverbel** [comment]
There is also Michael Schwern's 'Git for ages 4 and up' which is amusing https://www.youtube.com/watch?v=3m7BgIvC-uQ

**Comment by ChristinaLK** [comment]
Popping in - I think we'd like this kind of information to end up in the instructor's guide for each lesson eventually, but there are some folks working on a format for the guides right now, so for now this is a good place to store this info. :)

**Comment by kekoziar** [comment]
Closing old, inactive discussion.
