### ISSUE TITLE
Challenge at end of 01-backup.md - git repo inside a git repo

### ISSUE THREAD

**Issue by willingc** [swcarpentry/git-novice#33]
I'm wondering if there has been feedback from workshops on the last challenge of a git repo inside a git repo. While I like the challenge question of why it is a bad idea, I think that the steps are confusing for someone learning git. New learners of git (especially if they are learning bash too) are easily confused about where they are in the filesystem tree.

Recommendation: Remove the steps in this challenge and keep the question for students to ponder. Add a challenge that has the student moving through the history of the log using HEAD~1 would be a better exercise.

**Comment by jhamrick** [comment]
I agree, I think the steps in this challenge will be confusing to some students, especially if they are new to the command line.

> Add a challenge that has the student moving through the history of the log using HEAD~1 would be a better exercise.

I'm not entirely sure how this is related to a git repo inside a git repo -- could you clarify? Or are you just suggesting adding a different unrelated challenge?

**Comment by willingc** [comment]
@jhamrick different unrelated challenge. Merely an exercise to get users to understand 'HEAD' and how ~1 is syntactic sugar for moving back 1 from HEAD. For example, git show HEAD~2 displays the commit that is two before the HEAD.

**Comment by iglpdc** [comment]
I think that the challenge is fine, although it's true that the wording may be confusing. It happens quite often that learners are overwhelmed at the beginning of the lesson (they have to deal not only with `git`, but also with the command line) and some `git init` in the wrong place, either a repo inside a repo, or their entire home folder, or something similar.

Despite the fix is pretty easy, they aren't able to do it yet. I like the challenge because it's a very good moment to reinforce the idea that Git is folder-based.

I'd vote to keep the challenge, but rewording it to make it closer to the reality of the lesson. For example, `alpha` can be `planets` and `beta` could be `paper`, an independent repo for the paper associated to the planet research, or `moons`, a new repo on moon research. I'd also add a question on how to fix it, and stress that, in general, that's the way of fixing wrong `git init`'s. 

Maybe we should add also a corresponding note in the instructor guide.

**Comment by willingc** [comment]
@iglpdc I like your comments. If the challenge can be reworded to be more beginner friendly as you suggest, I agree that it would be helpful to reinforce the idea that Git is folder based. Do you wish to try to reword the challenge as you suggested? :smiley_cat:

**Comment by iglpdc** [comment]
Ok, @willingc, I'll send a PR tonight rephrasing the challenge.

**Comment by iglpdc** [comment]
Closing by #66.

**Comment by willingc** [comment]
@iglpdc Really like the changes that you made and merged. Nicely done. :cake:

**Comment by iglpdc** [comment]
Thanks!
