### ISSUE TITLE
Explain basic fork-edit-PR cycle in browser

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/git-novice#338]
Lots of newcomers will want to fork-edit-PR through the browser, so we should have a section (or separate stream?) explaining that cycle.

**Comment by vasudevanv** [comment]
How much depth are you looking to get into? I have some material that covers 
Fork -> Create branch -> Edit -> Submit PR -> Sync master with upstream (this needs a local copy command line). I can submit a PR if you like this depth.

**Comment by kekoziar** [comment]
I suspect this is `out of scope` for the lesson.  When `upstream` is added, it's definitely at `intermediate` level and so `out of scope` for a novice lesson, imo.

Also, since there has been no action on this for several years, I am going to re-add `intermediate` label, then close the issue.  If/when a second advanced git lesson is created, the developers can use the `intermediate` and `out of scope` labels to identify content that should be taught.
