### ISSUE TITLE
Using ungit or gitless as alternatives to git shell

### ISSUE THREAD

**Issue by Seanny123** [swcarpentry/git-novice#406]
Somewhat related to the discussion in #340 has anyone tried using [ungit](https://github.com/FredrikNoren/ungit)  and/or [gitless](gitless.com) instead of a pure git shell. 

Ungit is GUI for understanding git. 
Gitless is the output of a research project trying to simplify git.

I believe they both meet the requirements of Software Carpentry given they are:

- Open Source
- Cross platform

**Comment by unode** [comment]
Hi Sean,

I have tried gitless, saw a few videos on ungit and have tried many different GUIs..

On **gitless**:

I very much enjoyed the attempt of sanitizing git commands in gitless. There are more commands than with basic git but overall it makes for a more intuitive set of actions. The developers also decided to hide the staging complexity. As staging is one of the concepts that is sometimes hard to understand by learners, this helps in making it a little bit more beginner friendly.

On the other hand, roughly 60-70% of the commands do the same actions so you still have to learn those concepts. In this regard I think it adds little to bare git.

Finally, there is one big issue, gitless is not available for Microsoft platforms, only MacOS and Linux.

On **ungit**:

The graphical interface is helpful at having a visual representation of the commit history. It also provides mouse actions (click, drag&drop) to most commands.

While this can be helpful to avoid the command-line I think it brings little didactic value. Similarly to gitless you still need to have an understanding of the concepts behind git.

To some extent I also think that a graphical interface can be counter-productive since the learner can be distracted by eye-candy elements and unnecessary complexity (a graph of a busy repository can be quite scary).

Finally, while being open-source and cross-platform, installation is more complicated since you require nodejs, npm and git beforehand.

**Overall**, while these most tools aim at making git _easier_ to use, I personally don't think they succeed.
From my experience most of the difficulty with using git comes from understanding the concepts behind it and not necessarily the commands you need to type or the buttons you need to click.

**Comment by Seanny123** [comment]
Thank you for taking the time to reply @unode. Given your explanation, I now understand how these approaches don't solve the problem with understanding git.
