### ISSUE TITLE
Archiving data with exercise in 10-open

### ISSUE THREAD

**Issue by gallingerj** [swcarpentry/git-novice#409]
GitHub does not offer an archiving or digital preservation service. However, it's important that researchers deposit their data + code in a repository that is responsible for long-term maintenance of the files. Zenodo addresses this issue by offering a simple process to archive GitHub repositories. The [GH guide](https://guides.github.com/activities/citable-code/) for this process is straightforward and perhaps we could integrate a hands-on exercise into this episode. 

I think it's an omission to not mention the archival copy in "How to Find an Appropriate Data Repository?". The option to mint DOIs for GH repos with Zenodo is mentioned in "Can I Also Publish Code?". However, I only recently learned about the preservation copy through a data curation listserv _even though_ I teach this lesson routinely. I think these two sections need to be reworked so that students (and instructors!) understand what GH offers / does not offer for the long term. Framing it only in terms of citation is limiting.

**Comment by erinmgraham** [comment]
Hi @gallingerj, 

Thank you for your contribution to the git-novice repository. I noticed this issue has been inactive since 2018 and previous maintainers have labelled it as an enhancement needing help. Given it falls outside the current scope of the lesson and no one else has taken it up, I would like to close this issue to keep the repository clean and focused.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
