### ISSUE TITLE
Consider re-ordering Lesson 04 - Tracking Changes

### ISSUE THREAD

**Issue by csbailey5t** [swcarpentry/git-novice#411]
At the moment, the lesson seems to proceed by teaching the code and process before teaching the conceptual model underlying git commits, in this case understanding the idea of the staging area and the movement from untracked to tracked/staging area to part of the git history. This does mean that git commands create output for which there is not much conceptual framework to understand to explain to students, such as:

`use "git rm --cached <file>..." to unstage`

When this appears as a result of `git status` after `git add` early in the lesson, it could be difficult to explain should a student ask about it. There are ways to answer or delay answering. 

This points more generally to a question of whether the conceptual framework that explains git adds and commits should be front-loaded into the lesson, so that in teaching adding or committing, one could directly refer to how the git commands move information according to the conceptual model. For some people, having the visual that is introduced later in the lesson given and explained early might give the commands more meaning than they have abstracted from the model.

**Comment by misssoft** [comment]
After trying out teaching this session as my practice in the training course, I have the same concern that the conceptual framework should be taken in the front. The visual part is quite good and it would be better to bring up to the front for the learner to have an overview in the mind before trying the commands.

**Comment by allisongofman** [comment]
I agree with this feedback - I also did this session during my training course and found myself adding more theory and motivation at the beginning because going straight through didn't feel like it provided enough context or explanation for a novice. The analogy of the staging area and photograph would be useful earlier on.

**Comment by djinnome** [comment]
I couldn't agree more.  In fact, I found that drawing [visualizations on the whiteboard](https://marklodato.github.io/visual-git-guide/index-en.html) that provide context for the command is far more useful to do prior  to typing the command than afterwards.  It transforms the exercise from being a weird  incantation  that doesn't seem to have any visible consequences into a weird incantation that helps you navigate the nodes of the finite state machine that is git.

**Comment by esmesh** [comment]
I got the same feedback when doing this lesson in my checkout demo. "Explain commit in more detail the first time you use it." I had said that we were telling git to save the changes, but since we had introduced what the staging area was yet, going into more detail at that point would have been very difficult. This lesson really needs to set up the mental model of local -> staging -> repo (_and motivate why all three are needed!_) before teaching commands.

**Comment by kekoziar** [comment]
Thank you for the feedback.  A guiding principle of lesson development in The Carpentries is to [reduce cognitive load on learners](https://cdh.carpentries.org/guiding-principles.html).   The model is to demonstrate code then explain what happened.  The [instructor training states](https://carpentries.github.io/instructor-training/02-practice-learning/index.html), "presenting novices with a pile of facts early on is counter-productive, because they do not yet have a model or framework to fit those facts into. In fact, presenting too many facts too soon can actually reinforce an incorrect mental model."

Rearranging the episode to explain the concepts of the staging area before demonstrating a commit is the opposite of the model.  Additionally, there have been many improvements to the lesson in providing visualizations since this issue was opened.  I will leave this issue open for a short while for further feedback.

**Comment by kekoziar** [comment]
I'm going to close this issue.  Even when closed, comments may be added to issues.
