### ISSUE TITLE
Add a git fetch exercise?

### ISSUE THREAD

**Issue by jangari** [swcarpentry/git-novice#420]
Every time I teach this, participants ask how they can check to see whether origin has been updated before they try to git push so as to know in advance whether they're going to have to merge anything, or more generally just to compare their latest committed version with origin. 

Is it worth adding a small exercise showing git fetch, and then how to compare master with origin/master?

**Comment by naught101** [comment]
I agree. I also think it would be worth clarifying that `git pull` is equivalent to `git fetch && git merge origin/<upstream-branch>`. That would demystify `git pull` a bit, as well as clarifying the separation between merging branches and interacting with an upstream repo.

**Comment by esmesh** [comment]
[8 - Collaborating](http://swcarpentry.github.io/git-novice/08-collab/index.html) mentions fetch, but only in the solution to the review changes challenge at the end.

As @naught101 mentions, 'pull' should be clearly defined as a combination of 'fetch' and 'merge'.

**Comment by kekoziar** [comment]
I think `git fetch` is starting to go into _intermediate_ territory, which is _out of scope_ for a novice lesson.  Maybe if this were a full-day lesson, but since it isn't we need to be careful that this novice lesson doesn't go out of scope.

**Comment by erinmgraham** [comment]
Hi All, 

Thank you for your contributions and discussion around this issue. While this is a great idea, the issue's been labeled as an enhancement needing help since 2019. To keep our repository clean and focused, we are closing this issue for now.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!

**Comment by erinmgraham** [comment]
Hi All, 

Thank you for your contributions and discussion around this issue. While this is a great idea, the issue's been labeled as an enhancement needing help since 2019. To keep our repository clean and focused, we are closing this issue for now.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
