### ISSUE TITLE
Git w/RStudio

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/git-novice#424]
In restructuring an R lesson, it is losing one of the tip/challenge sections, which I think would go well at the end of the Using Git from RStudio episode.  I would like to submit a pull request to add the content.

The content is

Tip: versioning disposable output

Generally you do not want to version disposable output (or read-only data). You should modify the  .gitignore  file to tell git to ignore these files and directories. {: .callout}

Challenge
1.Create a directory within your project called  graphs .
2.Modify the  .gitignore  file to contain  graphs/  so that this disposable output isn't versioned.

Add the newly created folders to version control using the git interface.

Solution to Challenge
This can be done with the command line:
$ mkdir graphs
$ echo "graphs/" >> .gitignore

**Comment by VickySteeves** [comment]
Yes, I agree! In RStudio, if you have git installed on your computer, you can even just instantiate a git repository when you create a new project! Like so:

![screenshot from 2017-10-25 14-56-41](https://user-images.githubusercontent.com/10644777/32017447-bd5b314c-b994-11e7-8087-a86de363c0dc.png)

It's a nice way to combine the GUI aspect of using RStudio with the what you've outlined on the command line there (adding the graph files to .gitignore).

**Comment by djinnome** [comment]
There is a [similar functionality for Jupyter notebooks](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/gist_it), but instead of creating a full-fledged git repository, it pushes the jupyter notebook to gist, where it can be viewed online and shared with collaborators.

This would be a nice way to connect the python lesson with the git lesson.
I introduced this functionality at the last swc workshop I taught and it went well.

**Comment by kekoziar** [comment]
With approval, I will initiate a PR for the original request.

**Comment by iglpdc** [comment]
Sure, @kekoziar! Go ahead.

**Comment by kekoziar** [comment]
PR submitted.
