### ISSUE TITLE
01-backup.html & "A Better Kind of Backup"

### ISSUE THREAD

**Issue by mscook** [swcarpentry/git-novice#47]
The word "backup" is used twice (inclusive of the heading) in the prose. Why does this lesson contain backup in the filename and headings? I feel that this is confusing and, or associating git with backing up is dangerous.

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 03:32:00PM -0800, Mitchell J Stanton-Cook wrote:
> The word "backup" is used twice (inclusive of the heading) in the
> prose. Why does this lesson contain backup in the filename and
> headings?

The filename is independent of the lesson heading, but I think it's a
good idea to have them match fairly closely.  That helps folks working
in the project filesystem find the file they need (by looking at the
filename) and helps folks browsing the rendered lesson understand what
a page is about [1] (they're unlikely to *start* by reading the URL
;).

> I feel that this is confusing and, or associating git with backing
> up is dangerous.

Can you elaborate on this?  Personally, I feel like backing up with
Git is about as safe as it gets.  Along this vein, Linus says [2]:

> (Only wimps use tape backup: _real_ men just upload their important
> stuff on ftp, and let the rest of the world mirror it ;)

;)

[1]: http://swcarpentry.github.io/git-novice/01-backup.html
[2]: http://www.webcitation.org/6P8EBZqQX

**Comment by jiffyclub** [comment]
I think the conflation of version control and backups (which sometimes do mean different things) at this point is because a "backup" is something people have heard of. We need some kind of basis for introducing people to the idea of version control, and a backup is the closest thing people are familiar with.

**Comment by mscook** [comment]
In a traditional sense backup means (recoverable) duplicate. You only have a backup when you push to a 3rd party (Github). Even then anything that is placed in .gitignore will not be populated to the 3rd party.

**Comment by andreabedini** [comment]
Revision control is not a kind of backup (we better start teaching people what a real backup is) but I think the analogy can still be used to introduce it. Perhaps we can add a note explaining the limits of the analogy. Would that be ok with you @mscook ?

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 04:18:15PM -0800, Mitchell J Stanton-Cook wrote:
> In a traditional sense backup means (recoverable) duplicate. You
> only have a backup when you push to a 3rd party (Github). Even then
> anything that is placed in .gitignore will not be populated to the
> 3rd party.

Ah, good point.  The “let the rest of the world mirror it” bit is
important ;), Git just makes it easy to keep all the mirrors and forks
up to date.  In any case, it doesn't look like we actually talk about
backups much in this section.  Maybe we should replace the existing
“backup“ wording with “undo” (another familiar concept), since Git
does a good job there even without any remote repositories.  Of
course, we'll lose the alliteration…

**Comment by r-gaia-cs** [comment]
:+1: for the "undo".

**Comment by iglpdc** [comment]
I have mixed feeling about this. I agree "backup" is not the best description, but, as @jiffyclub says, it's important to refer to learners' previous knowledge. I'd prefer "backup" to "undo" also because the connotations of "backup": everyone knows they backups are gooood, so maybe this predisposes the learners to version control. (I've seen the opposite reaction though, with the argument that version control is only marginally better than services like Dropbox.)

**Comment by vahtras** [comment]
I think it is a great analogy. I really use git as a backup tool as well as for collaborative software projects. Indeed version control is not the exactly the same as backup but that is explained already in the title.

**Comment by wking** [comment]
On Thu, Feb 12, 2015 at 10:22:37PM -0800, Olav Vahtras wrote:
> Indeed version control is not the exactly the same as backup but
> that is explained already in the title.

As @mscook pointed out [1], it's only a backup if you have off-site
copies of your repository.  01-backup.md only covers local handling,
including “Restore old versions” (i.e. “undo”).  It never pushes the
local repository to a remote location, so if you never went on to
02-collab.md your workflow would be a great undo, but a terrible
backup.

I'm pretty sure the title does not make that clear, since “A Better
Kind of Backup” sounds wholly positive.  It would be different if the
subtitle was “A Better Undo, and Potetntially a Better Backup If You
Frequently Push To An Off-Site Remote Repository”, but that seems
unwieldy ;).

[1]: https://github.com/swcarpentry/git-novice/issues/47#issuecomment-74181860

**Comment by iglpdc** [comment]
Yet most people understand backup as scheduled copies of data to another hard-drive, e.g. using Time Machine, rather than redundant off-site copies.

In any case, I think there are very good arguments in this discussion. So, what about changing the title of the lesson to "Better undo, better backup"? It's shorter and has some punch. It also covers the main aspects discussed here: it's a better undo, and, if you backup you data properly and disaster happens, the fact that Git is distributed and folder-based will get you up and running again faster and easier.

**Comment by wking** [comment]
On Fri, Feb 13, 2015 at 10:54:07AM -0800, Ivan Gonzalez wrote:
> So, what about changing the title of the lesson to "Better undo,
> better backup"?

But nothing in this section speaks to backings.  Why mention it at
all?

> … it's a better undo, and, if you backup you data properly and
> disaster happens, the fact that Git is distributed and folder-based
> will get you up and running again faster and easier.

I'm not sure what you mean by “folder-based”, but the rest of this
sounds like “if you backup you data properly… Git [will work as a
backup]”.  You could replace Git with anything, and that would still
be true.

On the other hand, you could point out that Git makes it easy to
backup your data properly, because it makes it easy to synchronize
changes (vs. doing full copies with every push).  But there's no point
in talking about that in *this* section (it belongs in 02-collab.md).

**Comment by iglpdc** [comment]
El 13/02/2015, a las 14:23, "W. Trevor King" <notifications@github.com> escribi�:

> On Fri, Feb 13, 2015 at 10:54:07AM -0800, Ivan Gonzalez wrote:
> > So, what about changing the title of the lesson to "Better undo,
> > better backup"?
> 
> But nothing in this section speaks to backings. Why mention it at
> all?

I was trying to save the familiarity and good connotations that "backup" has for
most of the students. I think that if someone accidentally deletes a file, or corrupts
it in some way, there will look for a "backup" in a thumb drive, or pull out Time 
Machine, although this is strictly an "undo".

> 
> > � it's a better undo, and, if you backup you data properly and
> > disaster happens, the fact that Git is distributed and folder-based
> > will get you up and running again faster and easier.
> 
> I'm not sure what you mean by �folder-based�, but the rest of this
> sounds like �if you backup you data properly� Git [will work as a
> backup]�. You could replace Git with anything, and that would still
> be true.

I meant that the backup itself is easier with a DVCS like Git. I could just copy the 
whole folder somewhere else, without having to keep track of the versions
during the backup process.

> 
> On the other hand, you could point out that Git makes it easy to
> backup your data properly, because it makes it easy to synchronize
> changes (vs. doing full copies with every push). But there's no point
> in talking about that in *this* section (it belongs in 02-collab.md).

In any case, it seems that there is consensus on removing "backup" in favor of "undo"
@mscook, could you open a PR with this?

**Comment by iglpdc** [comment]
Thanks everyone for this discussion. After the split of `01-backup.md` in several files, the analogy between version control and a backup is much less stressed. In particular, the section names and headings no longer have "backup" on them. 

Also in the introduction to the lesson, in `index.md`, it's mentioned that version control works as a "undo" feature, which was pretty much the consensus reached at the end of the discussion.

I'm closing this issue as obsolete.
