### ISSUE TITLE
Licensing article link is broken

### ISSUE THREAD

**Issue by pllim** [swcarpentry/git-novice#474]
https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002598 gave me `ERR_CONNECTION_TIMED_OUT` error.

It is mentioned in https://swcarpentry.github.io/git-novice/11-licensing/

**Comment by nhejazi** [comment]
I was able to reproduce this -- thanks for reporting the broken link. It's hard to tell from the lesson (since the name of the article is not explicitly given) but I believe the article is available at this link: http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002598

A PR making this correction would be much appreciated.
