### ISSUE TITLE
Keeping the sentences about config email address together in the lesson

### ISSUE THREAD

**Issue by oelker** [swcarpentry/git-novice#487]
In 02-Setup, the line endings box text separates the example of Dracula using what is implicitly his real address, as his config address, from the discussion of github and email privacy which is below the line endings box text. It would help to keep all the content about choosing and entering an email address together in the lesson, and I think it would be better to move the sentences about github email privacy up before the text box about line endings (but if the whole thing were after, I think that might work, instead.) 

While we're at it, might also be worthwhile to show Dracula using a noreply email address from github instead of his real address, because I know that when I took this training as a student I was pleased to hear I could keep my email address private on GitHub... but then I totally missed the part about how to set up a noreply email in github and didn't configure it correctly while I was in training. Changing Dracula's email address to a pretend noreply email from github might convey this really effectively without adding length to the lesson.

**Comment by iglpdc** [comment]
Thanks, @oelker ! Sounds reasonable. We could move the paragraph about the alternative email right before the box on line endings.

Also to draw people's attention to the issue, we could make it a callout box, maybe entitled "Concerned about making your email public?", or "Keeping your email private", or something along these lines.

Once we are at it, I'd prefer to substitute this text:

>> If you elect to use a private email address with GitHub, then use that same email address for the user.email value, e.g. username@users.noreply.github.com replacing username with your GitHub one.

by the actual code that changes it.

Would you like to submit a PR with these changes?

**Comment by shals3** [comment]
I submitted a PR [ Update 02-setup RE: Privacy Concerns section #492 ] to address this.

**Comment by oelker** [comment]
This looks great, thank you so much!

**Comment by bmcandr** [comment]
I also think that the explanation of the process to locate the noreply email address on GitHub could be more explicit (Ep. 2, lines 71-72):

>If you are concerned about privacy, please review [GitHub’s instructions for keeping your email address private](https://help.github.com/articles/keeping-your-email-address-private/). **If you elect to use a private email address with GitHub, *then use that same email address*** for the user.email value, e.g. username@users.noreply.github.com replacing username with your GitHub one. You can change the email address later on by using the git config command again.

The instruction to "use that same email address" is quite vague and the example format that follows will not work for GitHub accounts created after July 2017 as the noreply addresses for newer accounts are prepended with a unique random number ID, e.g. `12345678+username@users.noreply.github.com` (see note [here](https://help.github.com/articles/about-commit-email-addresses/)). I suggest replacing the example with an explicit instruction to copy the noreply email address from the email settings page of the GitHub account. This reduces ambiguity and will work for all GitHub accounts regardless of account creation date.

Furthermore, I think it would be worthwhile to include a reminder about email privacy settings in Episode 7 ("Remotes in GitHub") (or the associated instructor notes) as this is where learners will attempt their first push which will fail if the email set in Git conflicts with their email privacy settings on GitHub. Like @oelker I too did not properly configure my email settings (possibly due to to the issues she outlined above) and Git threw a series of errors that required a dive into StackOverflow to correct.

**Comment by kekoziar** [comment]
Fixed with PR #492
