### ISSUE TITLE
No time for exercises

### ISSUE THREAD

**Issue by agzimmerman** [swcarpentry/git-novice#521]
I'm reviewing this entire lesson in detail for the first time, and I noticed that [this](https://swcarpentry.github.io/git-novice/10-open/index.html) is the only episode which allocates time for exercises. Despite this, I see many exercises in most of the episodes.

**Comment by iglpdc** [comment]
Yes, that should be chnaged. Older versions of the template had only one slot for time, so the current times include the "lecture" and the exercises. Also note that exercises are at the instructor's discretion, in the sense that instructors decide how many and which ones they do in each particular workshop. 

I would very much prefer to have timings for each individual exercise to inform the instructor of the time each tipycally takes, but it's kind of hard to guess.

**Comment by iglpdc** [comment]
@daisieh, @kekoziar, @nhejazi what do you think about this? Should we just:

- add the time all the exercises take,
- add the time that should be devoted to exercises in each episode, 
- find a way to add individual timings (very hard to maintain)?

**Comment by munkm** [comment]
Hi, new maintainer here! 

@iglpdc, of the three options you propose I would personally lean towards the first. Because exercises are left to the instructor's discretion, the quantity and choice of exercises assigned can vary between instructors. The first option seems like a good "hard limit" to give the instructors what the maximum amount of time that could be allotted to lessons, while also allowing this lesson repo to be maintained reasonably.

**Comment by iglpdc** [comment]
Sorry, @munkm ! 

The first one is my preference too. Does someone have other alternatives beside the ones I said?

**Comment by daisieh** [comment]
Ugh, I have never considered the time available for each exercise! If people have an idea of how long all the exercises take, then sure, that seems like a good way to go, but honestly I don't know if I'd bother including timings at all.

**Comment by alexanderzimmerman** [comment]
@iglpdc , thanks for looking into this. There are some fundamental considerations I think we should keep in mind:
1. During instructor training, frequent (e.g. every 5-10 minutes if I recall correctly) formative assessments were emphasized. I'm viewing these exercises as formative assessments.
2. The lesson has a schedule based on how long the episodes take. For this schedule to be useful, we should in some way account for time spent on formative assessments.

Are these clear?

I don't actually understand the difference between the first two options @iglpdc proposed, i.e. "add the time all the exercises take" and "add the time that should be devoted to exercises in each episode". Would someone please explain the difference to me? It seems that everyone else understands; but I'm new to this :)

@daisieh , the issue for me is that we're writing down that the exercises take zero minutes, which suggests that the instructor should not allocate any of the lesson time to exercises. So I would think either we do the due diligence of estimating time spent on exercises, or remove that field entirely. I don't know anything about the history of when the field (for exercise time) was added.

**Comment by munkm** [comment]
@alexanderzimmerman you're absolutely clear. It is important for instructors to assess the students' understanding of the material with these exercises and to provide another pathway for learning the material. If the schedule is to provide an estimate of time for each lesson to take, we need to address exercise time in some way (even if that includes a disclaimer that exercise time is not included). 

I'm going to elaborate on how I personally interpreted the options suggested by @iglpdc, but if my interpretation is different than somebody else's we can clarify that in this thread. 
- *adding the time all of the exercises take* is the maximal amount of time that the exercises should take, should all of them be assigned. It is likely that no instructor will assign all of the exercises in a lesson, so this could be a good bound for them to dedicate time for exercises, but not underestimate the time needed for lessons. 
- *add the time that should be devoted to exercises in each episode* is a different take on this. Rather than assessing the time that all of the exercises might take, this is a guideline time for the amount of time that an instructor should/could spend on exercises in a lesson. Because an instructor isn't likely to assign all of the exercises in an episode, they can pick and choose exercises that they feel strongly towards while still allocating a reasonable amount of time for exercises. This time doesn't include timing of specific exercises, nor does it suggest particular exercises to assign. However, it does give a consistent recommendation on the amount of time to spend on exercises in a particular lesson. 

My feeling is that the latter option is rather arbitrary, and it really is up to the instructor on how much time to spend on exercises, and in which lessons to spend more or less time on exercises.

**Comment by kekoziar** [comment]
I understand the need to solve this. As a new instructor, it was frustrating to see in carpentry lessons times that don't match lesson content (e.g. 30 minutes teaching listed on each episode, regardless of length) and/or no time listed for exercises. My colleagues and I realized we needed to go through lessons prior to delivering them - sometimes verbatim as a dry run - to determine timing and select which exercises we want to use.  

Having a suggested time for exercises, and balance between teaching/exercises is good pedagogy. Without an idea of how much time to take, sometimes new instructors will zip through the mechanics of something without explaining it, and learners become lost. More experienced instructors will understand the give and take of teaching/exercises, and adjust accordingly.  This is one of the reasons instructor training is so important.

The problem we will run into with having a total time as an upward bound (i.e. how much time does it take for all exercises listed in episode) is the same as the issue w/#3. Anytime an exercise is changed or added, we would need to re-determine the time required for all of the exercises.  

My preference is a suggested time allotted for exercises, with each exercise listed with their own times.  This would allow instructors to have an overview of what is suggested, plus an easy way of determining which exercises they want to include. I realize this is probably unattainable without a lot of work for designers and maintainers; plus, any contributors would need to think carefully about suggested changes.

What standard do the other lessons follow?

**Comment by iglpdc** [comment]
I don't think there is a SWC-wide standard, might be something to propose at the next maintainers meeting.

What about combining the info in the lesson with the instructor's guide (which in my opinion is underused - if this is a word)?

 We could have a table with the time per exercise in the instructor's guide. We could use blocks of 5 mins, or maybe something on a better scale (say under 2 mins for mutiple choice, 5 mins for short coding exercises, 10 mins for longer exercises).

Then at the top of the lesson we quoted either the total or the recommended time to spend in exercises.

In this way, instructors have all the info, but the lesson is not overcomplicated. Picking up exercises is just a matter of looking up the table and decide based on the time available.

Having a table for exercises could also be useful to indicate other things, such as which exercises are more important or potential problems with them.

In the future this could be standarize to provide support for other lessons.

**Comment by kekoziar** [comment]
> What about combining the info in the lesson with the instructor's guide (which in my opinion is underused - if this is a word)?

I like this idea, and it would solve many problems.  

The instructor's guide is underused, I think, because its location is slightly obfuscated; not everyone remembers the notes are there. The items in the top menu are all replicated in the lesson text (or on the workshop repository), except for some parts of "Extras." So, while it's there, often I forget about the top menu because I access the content through a different path.  I suspect others have similar experiences (anecdotally, I know my colleagues do).

**Comment by alexanderzimmerman** [comment]
Where is this "instructor's guide"?

**Comment by munkm** [comment]
Hey @alexanderzimmerman, I get to the instructor guide by using the dropdown from the menu at the top of the page. Under `extras` there is an option called `instructor notes`. In the URL it is labeled as a [guide](http://swcarpentry.github.io/git-novice/guide/). It's a nice supplement to the lesson and contains some tips for each lesson.

**Comment by TraciPopejoy** [comment]
> We could use blocks of 5 mins, or maybe something on a better scale (say under 2 mins for multiple choice, 5 mins for short coding exercises, 10 mins for longer exercises).

I think this would be very useful for classes with learners with a wide range of experiences. I would use a 10 min exercise to engage the advanced learners while allowing helpers the time to help learners behind. This makes the lesson customizable to the learners in the room. Putting this as a table within the instructors guide makes it easy to update. I didn't know about the instructors guide when I first taught. I find the timing of each episode very helpful for teaching, so I would rely on this table for future workshops.

**Comment by luisaforozco** [comment]
Hello, 
with #747 closed, do we still need this issue open?

**Comment by martinosorb** [comment]
With the new lesson template, I believe the distinction between exercise time and delivery time is no longer there.
