### ISSUE TITLE
Lesson 3: Add description for force delete in Solutions

### ISSUE THREAD

**Issue by krishnanj** [swcarpentry/git-novice#558]
In [[lesson-3/ Creating a Repository]](http://swcarpentry.github.io/git-novice/03-create/index.html) of Version Control with Git there is a solution at the end which describes how to remove the `.git` folder in the moons subdirectory.

Here the idea of recursive force deletion of folders is motivated using the command `rm -rf moons/.git`. However, from my skimming, there is no description of what is force delete or why we should use it here, only a warning to use it carefully. I think it is useful to have a longer description in the solutions section. If this issue is approved, I can submit a PR for the same.

On a similar note, I also noticed that there isn't a focus on removing files and directories with git  [correct me if I am wrong]. Perhaps its good to integrate a short description on `git rm` commands in one of the tutorials?

**Comment by nhejazi** [comment]
Thanks for bringing this up; I think this is a good point. In my teaching experience, usually the Git lesson is taught after a lesson that introduces shell commands, so this lack of explanation of `rm -rf` is possibly an artifact of relying on teaching in that order. I do think it's worth adding a short description of `rm -rf` as done in #560 so that the inherent danger in possibly abusing this command is less nebulous.

On another note, this is a fairly introductory lesson and I think `git rm` and related commands might be out of scope for this level of introduction. It would be nice to see a lesson covering some of these concepts but it might fall in an appendix section of the lesson or under advanced topics.

**Comment by nhejazi** [comment]
Resolved by #560.
