### ISSUE TITLE
Lesson 08: A better description of the reviewing process through GitHub

### ISSUE THREAD

**Issue by RolandMacDoland** [swcarpentry/git-novice#582]
Please delete the text below before submitting your contribution. 

---

In lesson 08, when it comes to review the changes made by a Owner broached in the exercises, can be a bit more explanatory in my opinion. I could be mentioned that the Owner can add the Collaborator as a `Reviewer` and that he/she gets notified through the email address set at the beginning. This has the advantage to engage with the reviewing process on GitHub and what would make a good review, and how to resolve a conversation for a satisfactory merge of the PR.

---

**Comment by munkm** [comment]
Hi @UCLGuichard. Thanks for the issue! Where exactly in lesson 08 do you think these changes should happen? Just after the `a basic collaborative workflow` callout box? One of the exercises in lesson 08 (`Comment Changes in GitHub`) talks a bit about interacting with Github and commenting on specific changes. What do you think about updating this exercise to be a bit clearer (some of the wording is unclear) and to also have one of the pair-programmers add their partner as a reviewer to solicit feedback on github?

**Comment by erinmgraham** [comment]
Hi @RolandMacDoland,

Thank you for your contribution to the git-novice repository. I noticed this issue has been inactive since 2019 and previous maintainers have labelled it as an needing more information. Given we still don't have more information and no one else has taken it up, I would like to close this issue to keep the repository clean and focused.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
