### ISSUE TITLE
Additional note on saving file in Nano

### ISSUE THREAD

**Issue by kfayesawyer** [swcarpentry/git-novice#610]
In going through [4 - Tracking Changes](http://swcarpentry.github.io/git-novice/04-changes/index.html), I hit a snag after typing my first line in Nano. The lesson says:

"Type the text below into the mars.txt file:

Cold and dry, but everything is my favorite color
mars.txt now contains a single line, which we can see by running:
$ ls
mars.txt
$ cat mars.txt
Cold and dry, but everything is my favorite color"

It's not explicit that you have to save and exit the file in order to run the next command. I'm happy to submit a pull request to fix it, if it's not too pedantic!

**Comment by tkphd** [comment]
Using a command-line text editor, like Nano, it's impossible to get the prompt `$` that allows you to type the next command, unless you first exit: the text editor occupies the entire terminal. However, updating the lesson to reflect that you have to save the file before you can run the next command might be helpful to those who are using a text editor that is not in the terminal, perhaps as a GUI or separate terminal application.

When teaching this lesson, I'm usually slow and careful to say, "I've opened nano to edit mars.txt... Now I'm typing in some details... then pressing -- look along the bottom, it's Ctrl+X to exit, then Y to save... Now we're back to the terminal."

**Comment by kekoziar** [comment]
Hello, @kfayesawyer and thank you for your comment.  At the beginning of episode 4, there is a reference to a section on working with text editors.  Those who are completing this in the workshop sequence (Shell then Git) won't necessarily need this, but those who are reading through on their own, or teaching it as a stand-alone lesson will have a link to the content covered in the shell lesson. 

> For a refresher on text editors, check out [“Which Editor?”](https://swcarpentry.github.io/shell-novice/03-create/) in The Unix Shell lesson.

This linked/referenced section explicitly lists how to save files in nano.  I agree with @tkphd in how I teach the lesson.  I am constantly stating "ctrl-O save, then ctrl-X to exit" since it slows me down and reinforces the Nano commands.  Nano will also provide a prompt if there are changes to the file that haven't been written out.  

I'm not against a generic comment that learners need to save their files in order to progress; however, I think it should be a generic comment.  

The `cat mars.txt` is the double-check to make sure the file was properly saved.

**Comment by JAISHAKTHI2310** [comment]
Pls tell how to save nano file in android
