### ISSUE TITLE
Episode 5 - History: References to HEAD~2 need to be updated

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/git-novice#621]
References to `HEAD~2` need to be updated to `HEAD~3`. 
Since we added/committed the spaceships directories at the end of Episode 4, at this point `HEAD~3` would refer to the first commit.

**Comment by munkm** [comment]
Quick question -- since the spaceships directories stuff in Episode 4 was in a callout do we assume that all instructors will do it? The lesson style guide (https://carpentries.github.io/lesson-example/04-formatting/index.html) says that the callout is an "aside", so this update is dependent on whether we assume that all instructors will follow it. 

I'm about to submit a PR to update these references, but it can be closed if we decide that a callout isn't in the main lesson.
