### ISSUE TITLE
Episode 6 - Ignoring Things: Exercise Ignoring Nested Files

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/git-novice#634]
The exercise prompt is
~~~
Given a directory structure that looks like:

results/data
results/plots

How would you ignore only "results/plots" and not "results/data"?
~~~

The construction of a .gitignore file that ignores one subdirectory has two solutions. One is trivial; the other is complex and, imo, requires intermediate to advanced knowledge of how git travels along directory paths. 

The first and easiest solution is to specify directly all directories to ignore.  e.g.
change `results/` to `results/plots` in the `.gitignore` file.

The second answer refers to the exclamation point operator, which has not yet been introduced.  This answer allows git to ignore everything in a folder except one subfolder.  The `.gitignore` file requires alternating statements between ignoring and unignoring more granular levels of the directory until the end directory that you don't want ignored is reached.

For this example, assume `results/data/` contains two files, `data.dat` and `data.txt`. You want to ignore everything in the `results` directory except `results/data/`.  The following sequence will allow `results/data` to be accessed, while ignoring all other `.dat` files and all other files and subdirectories within `/results/`.
~~~
*.dat
results/*
!results/data/
!results/data/*
~~~

If the asterisk at the end of the second line, `results/*`, is not included, everything in the directory will be ignored.

It is similarly important to include **both** the third and fourth lines.  The third line tells git it's okay to look at the directory `results/data/`, while the fourth line includes all files in the directory (overriding the previous exclusion of `*.dat` files. Oddly enough, git doesn't care what order the third and fourth lines are in.

I have now tested this on MacOS and GitBash with the same results.

That said, I'm not sure if this exercise is appropriate for the lesson because of the intermediate/advanced solution.  Perhaps the second solution should be listed as intermediate/advanced content, and a later exercise introduced, "Ignoring Nested Files, Part 2", with the explicit explanation and solution.  But, IMO, the answer is confusing and somewhat incorrect because it refers to a solution to a different exercise that over simplifies the exclamation point operator, and doesn't address how it works with directories.

**Comment by munkm** [comment]
Hm. This is indeed something we probably want to think about. I see why you're conflicted about the second solution -- and I am too. The current exercise does say that the exclamation point operator is introduced in the next exercise, so I'm tempted to leave it out to focus on the first solution (maybe with a nod to the next exercise so learners keep it in mind?). I do think the first (trivial) solution is appropriate for this lesson, and the second solution is beyond what we'd want to expect for a novice learner. 

That said, I don't see a problem with including more advanced material with some sort of disclaimer (e.g. "Intermediate difficulty solution:" or something).

Another thing I'm torn on is whether this exercise is implying that a person would want the dat files to be included in the `results/data` folder at all. I personally didn't interpret it that way (and the first solution would also need an exception to override the preexisting *dat line in the gitignore if this were the case). I'm not sure I'm interpreting this exercise the same as what you're saying in your statement here: 
> For this example, assume results/data/ contains two files, data.dat and data.txt. You want to ignore everything in the results directory except results/data/. The following sequence will allow results/data to be accessed, while ignoring all other .dat files and all other files and subdirectories within /results/.

That said, I can see a learner get tripped up with a dat file in the /data/ folder. Maybe we want to show the solution 
``` 
*.dat
results/*
!results/data/
```
and then say something about how *dat files are still ignored due to the first line and to override that you need to include `!results/data/*`? Or maybe this is more confusing? 

I think that introducing **both** the exclamation point and the override with the asterisk is including too much complexity for this exercise. If we want to do that then I think we should make a challenge exercise at the end of the lesson.

**Comment by kekoziar** [comment]
Oh, in my example I sorta combined the two exercises and added a .txt file to determine the actual structure of the statements in the ignore file (I also think it's bad form to switch to .data extension when the episode uses .dat).  That doesn't change the fact that creating exceptions to folders nested in previously ignored folders is tricky and a more advanced topic.

I am leaning toward taking out the second solution. Perhaps we can add the advanced topic to the discussion page, which addresses more advanced topics and reference that instead of adding a challenge exercise?  I know it took me more than a few minutes to test, check git documentation, and retest to get the correct ignore file syntax.

**Comment by munkm** [comment]
Maybe we should make another issue for the switch from .dat to .data files for the other exercises? I agree that switching from .dat to .data isn't a good convention and the other exercises would be improved by switching to follow the convention of the files earlier in the lesson. That said, the exercise for this issue doesn't have the .dat files at all so that might be out of the scope for this lesson. 

I agree that creating exceptions to folders nested in previously ignored folders is tricky and a more advanced topic. I absolutely think the four line solution is too much complexity for this exercise. I do think that showing the exclamation point exception is a more "advanced" solution, and absolutely would be worth adding to the discussion/instructor guide. We can add more detail in the instructor notes about the variant of this solution. 

That said, if we're introducing the exclamation point exception operator in the next exercise, I don't think that it's unreasonable to introduce this solution as an alternative solution: 
``` 
results/*
!results/data/
```

It is certainly more advanced than the other solution, but it is essentially a variation of the solution from the next exercise. I'm fine taking out this particular solution for this exercise, but I also think it would be worth putting a small statement at the end of the solution saying that there are alternatives with other operators that users might want to take (e.g. mentioning that they might want to look into ! and ** operators as alternatives) would be good. 

Alternatively, we could make an additional exercise after the exercise that introduces the exclamation point operator to show how the operator works with folders. We could use this same prompt but explicitly ask users to find a solution with the exclamation point operator.

**Comment by munkm** [comment]
I can make a PR that does this (with the added exercise and the simpler solution) if you think this is a reasonable approach/solution.

**Comment by kekoziar** [comment]
I think that sounds reasonable. What do you think about adding a link to the official documentation for [git ignore](https://git-scm.com/docs/gitignore)?

**Comment by munkm** [comment]
I like that idea! Should we do it in the body of the lesson or in the instructor guide?
