### ISSUE TITLE
Refer core.editor config to official list

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/git-novice#671]
Hello :-)

In [02-setup](https://github.com/swcarpentry/git-novice/blame/04ffeff2715ba95433751f6bb0b2df978d6ed3af/_episodes/02-setup.md#L78-L91) we maintain a long list of `git config core.editor …` commands.

Because [Git's manual now has an official list](https://git-scm.com/book/en/v2/Appendix-C%3A-Git-Commands-Setup-and-Config#_core_editor), how about we reduce ours to `… "nano -w"` as [our default](https://github.com/swcarpentry/git-novice/blame/04ffeff2715ba95433751f6bb0b2df978d6ed3af/_extras/guide.md#L99-L107) example and refer to the manual?

IMHO, this is a rare chance to [reduce](https://github.com/swcarpentry/git-novice/blame/04ffeff2715ba95433751f6bb0b2df978d6ed3af/CONTRIBUTING.md#L93) the amount of content we have to maintain, without any risk, because that official list can be maintained by a wider community, with particular incentive for the editor developers themselves to keep "their" command up-to-date ;-)

**Comment by kekoziar** [comment]
Hmmm. I like this, but I also worry about it. 

Git's exhaustive list isn't exhaustive (we include Notepad++ and Emacs, where they don't).

I like how we list the two different config commands for 32- vs 64-bit editors; ours is easier to cut and paste, whereas git's list requires full reading of the page (they don't even asterisk the 64-bit commands to refer to the note, so someone looking for a 32-bit command could leave the page in frustration). Which leads to...

Do we really want learners who are on the lesson page to leave the lesson pages as part of the lesson?  Granted, git-novice has plenty of links to outside references and resources; more than I've seen in other lessons.  But, I also know we are careful about outside links, especially those that don't support good pedagogy.  git-scm.com may be *the authority* on git, but they aren't exactly the best at explaining how to use git, especially for a novice learner; nor are they the best at website design.  For example, instead of the "exhaustive list" being exhaustive, the information is located in at least three different places, one of which isn't even on the same page (I now see where the Notepad++ and Emacs configuration commands are located).

So, removing the table from the lesson may condense the text, but are we really saving time in the lesson? We’re not reading through the list of text editors (or I hope no instructor sees that list and thinks to read through it), but it is there for reference, to ease setup. Removing the table in favor of this link could actually add time to the lesson.

While I think a link to git's non-exhaustive table would be nice, I'm not sure it should replace the table in the lesson.

**Comment by katrinleinweber** [comment]
> they don't even asterisk the 64-bit commands

PRs to expand that table can also be sent to https://github.com/progit/progit2/blob/master/C-git-commands.asc#L40. I'm on it as well.

> we are careful about outside links links, especially those that don't support good pedagogy

It's a list on our page vs. a list on their page. The pedagogic argument doesn't count for a mere list of "reference, to ease setup". Quite the opposite IMHO: Why are we writing our own _lessons_, instead of upgrading the official docu with pedagogically valuable content? Different issue/PR, though; Let's not discuss that here.

> nor are they the best at website design

It's list/table on our page as well.

The core question is whether you want to "reduce the amount of content we have to maintain, without any risk".

**Comment by kekoziar** [comment]
@katrinleinweber I think you missed the conclusion of my post.  There is risk of adding time to the lesson:

> So, removing the table from the lesson may condense the text, but are we really saving time in the lesson? We’re not reading through the list of text editors (or I hope no instructor sees that list and thinks to read through it), but it is there for reference, to ease setup. Removing the table in favor of this link could actually add time to the lesson.

"reduce the amount of content we have to maintain," in this case is not the same as removing material covered in the lesson. It's just redirecting instructors and learners to a site that does not display the content in as organized fashion as the lesson.

While I think a link to git's non-exhaustive table would be nice, I do not think it should replace the table in the lesson.

**Comment by munkm** [comment]
> "reduce the amount of content we have to maintain," in this case is not the same as removing material covered in the lesson. It's just redirecting instructors and learners to a site that does not display the content in as organized fashion as the lesson.
> 
> While I think a link to git's non-exhaustive table would be nice, I do not think it should replace the table in the lesson.

I agree with this. Considering this setup is required for learners to continue on the lesson, I think it is a mistake to move this content to be maintained by another organization. I personally think linking to outside references is helpful for supplementary or more detailed information, but text editor setup really isn't in that category.

**Comment by kekoziar** [comment]
Oh, you're right, @munkm.  I was (selfishly) thinking of maintaining the link as a lesson-maintenance reference; but, it's recorded in this issue which we can still refer to in the future. It really doesn't fit as supplementary or more detailed information for the lesson.

**Comment by katrinleinweber** [comment]
> maintained by another organization

It's maintained by whoever chooses to do it ;-) I actually think the ["exhaustive" is a tounge-in-cheek way to motivate](https://meta.wikimedia.org/wiki/Cunningham%27s_Law) whoever sees something missing to correct that.

**Comment by munkm** [comment]
My use of maintainer was referencing people who have merge and commit rights to the repository. As far as I know, none of the git-novice maintainers have those permissions for the git manual. If an issue arises for the setup of text editors that are relevant to this lesson, none of the maintainers of this lesson can quickly fix it because we'd be dependent on another organization to merge a proposed fix. That concerns me.

**Comment by kekoziar** [comment]
My concern stems from experience teaching this lesson. In our workshops, there are often two or three different text editors (including nano) being used by learners. Steering away from the lesson as part of the lesson __will add time to the lesson__. 

I don't think we should be expected to maintain a different organization's materials as part of our duties for The Carpentries, so I won't address anything about that beyond this statement.

**Comment by munkm** [comment]
> I don't think we should be expected to maintain a different organization's materials as part of our duties for The Carpentries, so I won't address anything about that beyond this statement.

I agree.

**Comment by katrinleinweber** [comment]
> expected to maintain a different organization's materials

You're not expected to, you have the possibility.

> we'd be dependent on another organization to merge a proposed fix. That concerns me.

When you try submitting a reasonable PR there, you'll find that your concern is unfounded.
