### ISSUE TITLE
Incomplete output from `cat` in Episode 4, "Committing Multiple Files"

### ISSUE THREAD

**Issue by LouiseABowler** [swcarpentry/git-novice#695]
The first step of the "Committing Multiple Files" exercise in [Episode 4](http://swcarpentry.github.io/git-novice/04-changes/index.html) is to add a new line of text to `mars.txt`. The command `cat mars.txt` is then used to examine the contents of the file before proceeding.

The solution shows that the output of the `cat` command should be
```
Maybe I should start with a base on Venus.
```
but it actually shows all the text in `mars.txt`, which at this point is
```
Cold and dry, but everything is my favorite color
The two moons may be a problem for Wolfman
But the Mummy will appreciate the lack of humidity
Maybe I should start a base on Venus.
```

When I went through the exercise I wasn't sure whether the text had intentionally been cut for brevity, was unintentionally incomplete or whether I should have replaced the earlier lines in the file. (I'd guess not the last option as the solution's commit log says "2 insertions" only.) If someone could clarify, I'd be happy to open a PR to fix 😄

**Comment by tdido** [comment]
Seems like there is a related problem also in the [next episode](http://swcarpentry.github.io/git-novice/05-history/index.html). Right at the beginning, the output of `cat mars.txt` after adding a new line as indicated is listed as:
```
Cold and dry, but everything is my favorite color
The two moons may be a problem for Wolfman
But the Mummy will appreciate the lack of humidity
An ill-considered change
```
Ignoring the `Maybe I should start a base on Venus.` line added in the exercise @LouiseABowler mentions.

Maybe a PR to get all this back in sync is needed?

**Comment by kekoziar** [comment]
Since instructors will pick and choose different exercises to complete during workshops, the output varies. To avoid the lesson becoming cluttered by reflecting all possible scenarios of zero to all exercises, the lesson output reflects changes made by the lesson, but not the exercises. I hope this explanation clarifies any confusion.

**Comment by tdido** [comment]
I see. That would explain my case then, but @LouiseABowler 's comment still stands, since the exercise should show the content that has been added during the main lesson body, right?

**Comment by kekoziar** [comment]
The exercises don't always show the content from the main lesson body.  They are created to supplement, but not necessarily extend content in the episode.  

While exercises are listed at the end of the episode, each instructor may identify which exercise(s) they want to use during their workshop and when.  In this case, _when_ the exercise is covered during the workshop will predicate the output of `cat mars.txt`.  Depending on placement, `cat mars.txt` may show zero to four lines preceding `Maybe I should start with a base on Venus.`  Since we can't include all possible variations, we chose to only output the line added during the exercise.

How about adding a note in the exercise solution along the lines of, 

> This `cat mars.txt` only reflects content added during the exercise. 

?

**Comment by tdido** [comment]
I see. I guess my confusion spans from the assumption that the lessons should be easily used as a tutorial. In that case this confusion would arise. If you're being led by an instructor I agree it would not really matter.

Your note idea seems to be a good one. But how about a more generic:

> The output from `cat mars.txt` may vary depending on the specific commands you executed in previous exercises

**Comment by kekoziar** [comment]
How about

> The output (above/below - depending on placement) from `cat mars.txt` reflects only content added during this exercise. Your output may vary.

?

**Comment by tdido** [comment]
Yes, that should work. Not sure I understand the part between parentheses, but the note will surely be of help.

**Comment by kekoziar** [comment]
The parenthetical remark indicates that the word above or below should be added to the sentence depending on placement in relation to the output.
