### ISSUE TITLE
Suggestions on git large file system and submodule

### ISSUE THREAD

**Issue by sunyi000** [swcarpentry/git-novice#701]
I would like to make the following 2 suggestions

1. in episode 10 https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/10-open.md
it mentioned a little on Git LFS. I think it should also mention that the recommended size of a repository is < 1Gb. Git should be used for source code, not as a storage solutions. Storing graphical/binary assets in git is not a good idea and should not be encouraged.

2. Maybe worth adding a section/episode on 'git submodule'. 
It is useful when a project depends on another one in a separate repository.

**Comment by munkm** [comment]
Hi @sunyi000, 

1. git should absolutely be used for source code, and not storage solutions. However, for things like test data git LFS can be extremely helpful. I don't think this particular solution is "encouraging" our learners to store data in git. That said, I think it would be a helpful addition to this particular exercise to add a sentence talking about best practices for repositories (including not tracking datafiles). 

2.) I think 'git submodule' is far outside of the scope of the git-novice lesson, but certainly could be included in an intermediate or advanced lesson.

**Comment by erinmgraham** [comment]
Hi @sunyi000 ,
Thank you for your contribution to the git-novice repository. We noticed that this issue has been inactive since 2019, and the previous maintainer asked for a sentence to add to address #1 and #2 falls outside the current scope. Given no one else has taken it up, I would like to close this issue to keep the repository clean and focused.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
