### ISSUE TITLE
Is using "origin master" really necessary?

### ISSUE THREAD

**Issue by markgdawson** [swcarpentry/git-novice#716]
I'm not convinced (in the current form of the notes) that specifying "origin master" everywhere adds enough value to be worth including.

Typically, I'd always write "git pull" or "git push" and never worry about the "origin master" part.

I can't think of many sensible cases where a user would want to specify the "origin master" variant:
- someone might be on one branch whilst pushing another, but I don't think we've taught enough here to worry about that.
- if you're on a branch other than master that you've created locally, then you get the potentially confusing message:
```
fatal: The current branch another-branch has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin another-branch
```
I admit this is slightly confusing, but I don't think that this message is worth teaching that we should be typing "git pull" and "git push" everywhere.

Anyone else have any thoughts on this?

**Comment by omsai** [comment]
`git push origin master` is always guaranteed to work whereas you will always see the `git push` message you quoted when your remote is a bare repository and the master branch does not yet exist on the remote.  You can reproduce this as follows:

```console
omsai@xm2:~$ cd /tmp/
omsai@xm2:/tmp$ mkdir repo-local
omsai@xm2:/tmp$ cd repo-local
omsai@xm2:/tmp/repo-local$ git init
Initialized empty Git repository in /tmp/repo-local/.git/
omsai@xm2:/tmp/repo-local$ touch test.txt
omsai@xm2:/tmp/repo-local$ git add test.txt
omsai@xm2:/tmp/repo-local$ git commit -m "Initial commit"
[master (root-commit) 9aa30c7] Initial commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
omsai@xm2:/tmp/repo-local$ git remote add origin /tmp/repo-remote
omsai@xm2:/tmp/repo-local$ mkdir /tmp/repo-remote
omsai@xm2:/tmp/repo-local$ git -C /tmp/repo-remote init --bare
Initialized empty Git repository in /tmp/repo-remote/
omsai@xm2:/tmp/repo-local$ git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

omsai@xm2:/tmp/repo-local$ git push origin master
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 217 bytes | 217.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To /tmp/repo-remote
 * [new branch]      master -> master
omsai@xm2:/tmp/repo-local$ 
```

Talking about "origin master" does not add much cognitive load.  You should have already explained what "master" is when you explain the first commit message, and origin is the name we gave to the remote URL:

```console
omsai@xm2:/tmp/repo-local$ git remote -v
origin	/tmp/repo-remote (fetch)
origin	/tmp/repo-remote (push)
omsai@xm2:/tmp/repo-local$ 
```

**Comment by M4rkD** [comment]
Thanks for your comment @omsai, much appreciated. You're absolutely right of course, I neglected the case of pushing an existing local to a bare remote, that does complicate things.

Having said that, I'm a little bit convinced, but not fully convinced (yet?).

The most likely scenarios I see for this is a new repos on services like github, bitbucket etc - but they're pretty good at being explicit about thow to do it. The github bare repo page (for example) shows a very neat breakdown of how to upload existing (and new) code. I just don't see this as a major stumbling block.

Otherwise they create a bare repo themselves (using commands we haven't taught them), or someone else creates it for them, or they start messing around with remotes. But to my mind these are all beyond the scope of the material.

I suspect there are other cases that I'm forgetting, but I can't think of anything else? Are there other important cases I've overlooked here?

As to the comment
> Talking about "origin master" does not add much cognitive load. You should have already explained what "master" is when you explain the first commit message, and origin is the name we gave to the remote URL

I'm interested in the opinion of the community here, because this is different to my experience. I've not found master trivial to explain without branches. I certainly haven't got a foolproof sentence to introduce it, I would be interested if anyone else does. If it exists, the notes would very much benefit from this.

Same goes for origin and mltiple remote, but I find this one find easier to get away with.

**Comment by devnich** [comment]
Putting on my developer hat for a moment, I work with a lot of small remote repositories, many of which start out as bare repos. I think it's a common use case in research computing to have a lot of small projects that start out as repositories on your local machine and then get pushed to Github or Bitbucket.

For people using this workflow, specifying the complete `git push origin master` command is (a) necessary, and (b) really annoying. I personally set the upstream as soon as Git suggests `git push --set-upstream origin master`, and thereafter use `git push` and `git pull` as @M4rkD suggests.

In our Carpentry lessons on Git, I've found that the Github section of the lesson is a natural place to talk about this configuration step. The section already has the students create the bare repository, add the repository information to their local configuration, check the repository configuration with `git remote -v`, and push with `git push origin master`. We have our students commit a second change and attempt to push it with `git push`. When they get the warning message, we explain that they can permanently add the upstream option to their configuration, which saves them having to type the fully-specified command every time. They set the upstream with `git push --set-upstream origin master`, check the configuration update with `git remote -v`, and then test it by pushing a third commit with a simple `git push`.

We do have to introduce the concept of branches in order to explain what `master` is doing in the configuration. At this point in the lesson, the students are fairly comfortable with the idea that Git lets them move backward and forward through a project's history or timeline. With this as background, we can generally say something like, "You can create alternate project timelines. These are called branches. They can be useful if you want to try something that might break your code, but you want to have access to a working version of your code while you do it. Right now you only have one branch, which is called `master`." Since the curriculum doesn't include branching and merging, we leave it at that and tell people to come talk to us after the class if they want to know more about what's possible. So far, the students have been satisfied with that level of explanation.

**Comment by M4rkD** [comment]
I have to say I agree with @devnich, I would very much like to see this changed.

I'm not aware of any developers that would default to the (more verbose) "git push origin master" as a habit/default. And if I ever meet one, I would imagine that it would be something like "you know you can just use git push", and they'd never look back.

If for some reason I don't have an upstream specified, the sensible approach to me is to set an upstream. I would imagine that this is what most developers do? It just seems to me a more convenient, powerful, and simple approach. I don't see it at more cognitive load (they can just copy the message from the suggestion that git makes, and it'll work).

Additionally, we're deliberately/knowingly providing a different set of instructions that services like github and bitbucket are giving. We're saying "no, don't do that, do this instead". Why? I imagine, many people are just going to copy the github upload text anyway. I would.

Inevitably, they'll also likely run into people doing "git push" and "git pull", then probably end up using copy/paste on the --set-upstream option anyway. The message is fairly easy to guess what it does:
```
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin <name-of-current-branch>
```

Even if all they take away from it is "copy and paste the command it asks you to", I still think that overall it'll make git a better experience for them.

In fact, I vaguely remember when I was newer to git, and understood it much less, I would just occasionally copy/paste these suggestions it gave and not give it a second though. Everything would work as I expected.

The main downside I see to this this approach is that it means that if in the future I want to be pushing a single branch to multiple different remote branches, I need to understand that I can provide this to git push/pull. I would think a callout would be sufficient to point this out, if needs be.

**Comment by kekoziar** [comment]
Hello, @markgdawson  and @devnich.  I agree with what @omsai wrote; the `origin main` introduces minor cognitive load and reinforces to new learners what it means to work with a very basic remote.  Introducing `git push --set-upstream origin master` is a step into advanced working with repositories, including multiple repositories and branches.  

Feel free to work on an advanced Git lesson that covers branches and multiple repositories.
