### ISSUE TITLE
Lesson 3: revise instructions for using rm

### ISSUE THREAD

**Issue by mattipt** [swcarpentry/git-novice#720]
The commands suggested in the "Correcting git init Mistakes" section of Lesson 3 should be revised.

First, it suggests that the command `rm filename` would "remove files from the working tree and not from your working directory". But then the explanation immediately below (file has to be in sync, `-f` option) clearly pertains to the `git rm` command, not the `rm` command. From context it seems likely that the `rm` command is what's called for here, but the explanation is a red herring.

In addition, the section suggests twice using `rm -rf` to remove directories. I don't think there is any reason to use the `-f` option here; it's probably one of those options that one should not commit to muscle memory.

**Comment by kiwifb** [comment]
I personally think it should be reworded more carefully. Because really the text box explanation involves things that we are only starting to explain properly in the next episode.
So, I would simplify the explanation and concentrate on the usage of command line to remove files and refer to later lessons.

**Comment by kekoziar** [comment]
Resolved in https://github.com/swcarpentry/git-novice/pull/753
