### ISSUE TITLE
Should text in "conflicts" examples be representative rather than self-describing

### ISSUE THREAD

**Issue by edbennett** [swcarpentry/git-novice#727]
Up until the episode on [conflicts](http://swcarpentry.github.io/git-novice/09-conflict/index.html), all examples are representative of how git might be used in a real workflow, with Dracula making notes vaguely related to the hypothetical scenario being worked on. However, in the Conflicts episode, this abruptly switches to self-describing examples, with text like "This line added to Wolfman's copy"—this is not motivated, and is likely to cause additional cognitive load on learners (and also makes it harder for instructors to teach it). When the merge conflict is resolved, this makes it less clear to the learner what the resolution means.

I feel it would be better to have two relatively motivated "in-universe" changes made by Wolfman and Dracula that are inconsistent with each other, then these are resolved by finding a middle ground.

Even better would be if the changes were each two-line changes, and only one line was inconsistent, so that we could show that some changes could be kept—this would make it clearer why both versions are shown in the editor. Otherwise we may be giving the mistaken impression that you have to delete all conflicting lines and start from scratch.

(I'm happy to draft the changes to the lesson if we agree that this is something worth doing.)

**Comment by kekoziar** [comment]
Feel free to draft something.  When I first went through this episode by myself, I found self-described text like "This line added to Wolfman's copy" helpful because it allowed me to easily keep track of the changes I made in the two separate repositories on my computer.  This allowed me to concentrate on what was going on with Git; since the text was self-described and I didn't have to refer back to any notes about "who" made which change, my cognitive load was reduced.  

When we get to this section during live-workshops, there is usually a helper who will make a change to the file while I'm demonstrating a change to the learners.  The changes are usually fun and reflect the rapport created during the workshop.

However, if you're able to create something that is aligned with the story while providing an easy way to differentiate changes made by the different characters, I think it will be an improvement.

**Comment by erinmgraham** [comment]
Hi @edbennett ,

I know this issue was related to 829 that was closed recently in preparation of the new workbench lesson infrastructure. I will close this issue as well but if you believe this issue still needs attention in the new storyline, please feel free to create a new PR with updated details.

Thank you for your understanding and support!
