### ISSUE TITLE
Episode 10: Changing from "Open Science" to "Open Research"

### ISSUE THREAD

**Issue by rainsworth** [swcarpentry/git-novice#750]
This issue opens a discussion on reframing [Episode 10: Open Science](http://swcarpentry.github.io/git-novice/10-open/index.html) as Open Research.

As more research domains become data and computationally intensive and engage in Software Carpentry lessons, it would be more inclusive to change the language from "Open Science" to "Open Research". 

The only real changes to the episode would include:
- Renaming the episode title to "Open Research"
- Changing the "scientist" persona in the lesson to "researcher"
- Optionally adding a sentence to explain that the Open Science movement is transitioning to Open Research or Open Scholarship to be more inclusive of all research domains

After any further discussion, if this is something that the maintainers agree with I would be very happy to submit a pull request!

**Comment by HaynesStephens** [comment]
**Part of my check-out process**
I agree with the promotion of inclusion that this issue raises and I believe that the episode could be reworded to be inclusive to more people. In furthering the discussion, I don't know if there are formal definitive differences between "scientist" and "researcher" somewhere that I am unaware of, but I believe that someone conducting research that involves data-science techniques would qualify them as a scientist. My proposed alternative stems from wanting to encourage more people who use scientific research methods, however partially, to think of themselves to some degree as a scientist. 
I propose keeping the terms as "science" and "scientist," but to @rainsworth 's point, I would add a sentence near the top of the episode that echos what she says at the beginning of her comment: "As more research domains become data and computationally intensive, the term 'scientist' broadens to encompass researchers in more fields who use scientific (or data-science) techniques in their work." 

Regardless, I agree with @rainsworth to reexamine the inclusive language of the episode and I believe their proposed changes (especially the third point of an added sentence) would improve the quality of this lesson.

**Comment by peterjc** [comment]
Is the proposed language means to be more inclusive by covering humanities (etc) - as well as more applied science?

**Comment by LOkelo** [comment]
**Part of my check-out process**
I agree with @rainsworth and @HaynesStephens on their thoughts and views expressed and shared in the preceding paragraphs above
  
My own contribution to Episode 10: Open Science as Open Research is to suggest additional information to the section "how to find an appropriate data repository "

The section rightly states "Surf the internet for a couple of minutes and check out the data repositories mentioned above: Figshare, Zenodo, Dryad. Depending on your field of research, you might find community-recognized repositories that are well-known in your field"

I wish to suggest that there has been a significant rise in the number of credible open science (or open research as suggested earlier by @rainsworth) African owned and hosted data and code repositories that have  since begun to emerge and therefore it is worth checking out and considering using such data repositories when it comes to efforts directed towards finding an appropriate data repository

This suggestion might be helpful and of interest particularly to research output about Africa, from both African and non-African researchers based on and off the continent

It is worth noting that open science transcend boundaries and nationalities, therefore all efforts should be aimed at increasing the visibility of all science and such measures should include ensuring that a good number of data repositories are hosted and owned on African territory while welcoming all meaningful contributions from the global science community

**Comment by kekoziar** [comment]
I think making the change from Open Science to Open Research is a good suggestion.  I happily welcome a PR which makes this change.  (as an aside, PRs should be limited to one change per PR - unless it's minor grammar/spelling corrections.)

I think the suggestion on expanding the section on repositories, while tangential to the original topic of this issue, is its own topic.  I encourage further discussion regarding international repositories - although I think the discussion warrants its own issue.

**Comment by LOkelo** [comment]
> I think making the change from Open Science to Open Research is a good suggestion. I happily welcome a PR which makes this change. (as an aside, PRs should be limited to one change per PR - unless it's minor grammar/spelling corrections.)
> 
> I think the suggestion on expanding the section on repositories, while tangential to the original topic of this issue, is its own topic. I encourage further discussion regarding international repositories - although I think the discussion warrants its own issue.

Thank you very much @kekoziar this guidance is much appreciated and i shall do so (i.e. with regards to a separate issue) thank you

**Comment by erinmgraham** [comment]
Hi All, 

Thank you for your contributions and discussion around this issue. We notice the conversation came to a halt in 2021. 

To keep our repository clean and focused, we are closing this issue for now.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
