### ISSUE TITLE
Suggestion for improving the graphic in the Remote in GitHub lesson

### ISSUE THREAD

**Issue by kyliebalotin** [swcarpentry/git-novice#771]
The final image in the [Remotes in GitHub](http://swcarpentry.github.io/git-novice/07-github/index.html) lesson might be improved by including an arrow to show how the pull command works/links the GitHub repository to the local repository. I noticed that all the other commands were included in the graphic except for the pull command. It might also be a good reminder that this step is important when collaborating with others when the learners move to the next lesson.

**Comment by kekoziar** [comment]
The graphic represents the actions the learners have made.  They have not pulled anything yet since they just set up the remote and connected the local repository to it. 

However, feel free to make a graphic for the [collaborators](http://swcarpentry.github.io/git-novice/08-collab/index.html) episode, where the collaborative workflow is listed (`pull`, `add`, `commit`, `push`).

**Comment by erinmgraham** [comment]
Hi @kyliebalotin ,

Thank you for your contribution to the git-novice repository. We noticed that this issue has been inactive since 2021 when it was labelled as help wanted to make an alternative graphic. Since no one has taken it up and to keep our repository clean and focused, we are closing this issue for now.

If you believe this issue still needs attention, please feel free to reopen it or create a new one with updated details.

Thank you for your understanding and support!
