### ISSUE TITLE
Adding a keypoint to _episodes/11-licensing.md about LICENSE file in repos

### ISSUE THREAD

**Issue by willblev** [swcarpentry/git-novice#791]
Perhaps we can add a keypoint to [`gh-pages/_episodes/11-licensing.md`](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/11-licensing.md) for [lesson 11 about Licensing](https://swcarpentry.github.io/git-novice/11-licensing/index.html)?

On the [Reference page](https://swcarpentry.github.io/git-novice/reference.html), the top section "Key Points" is automatically populated using the `keypoints` entries in the yaml header of each episode. While the Licensing episode goes in to detail about the purpose of a LICENSE file in a repo, since this is not included as a keypoint entry, it is absent on the Reference page. 

A similar keypoint already exists for the [following lesson about citations](https://github.com/swcarpentry/git-novice/blob/gh-pages/_episodes/12-citation.md), so I think that this information belongs here as well.

**Comment by kekoziar** [comment]
@willblev  Key points usually address the learning objectives and/or questions in the episode.  Will you expand on how your key point does that?

**Comment by willblev** [comment]
@kekoziar Happily! The specific learning objective that this key point represents is that the learners will understand that the file named "LICENSE" in a GitHub repository is used to specify the type of license. Perhaps it's intuitive

**Comment by kekoziar** [comment]
If the learning objective is intuitive, wouldn't the key point also be intuitive?  

What I'm taking a long way of getting to is the changed text in the PR (_Add a LICENSE file to a repository to explain how your work can be used by others_) refers to something that doesn't occur in the episode.   The episode doesn't prompt learners to add a license file to the lesson.  The episode focuses on what content should be in a license file, and different ways of choosing the content. Since different license text shouldn't be something that is skimmed, but thoroughly read, I'm not sure learners would be at a place to quickly add a license file.  Although, for this particular repo, `planets`, one might make the case that since they're making it using instructions in the swc lesson, that the repo should inherit the license of the original lesson...?

**Comment by willblev** [comment]
@kekoziar Now I see your point! My [original PR text](https://github.com/swcarpentry/git-novice/pull/792) is definitely describing _creating_ a LICENSE file during the lesson. As you also mention, a LICENSE file _could_ be added to the `planets` repo in this episode, but *this extra step would increase the time needed to cover this episode which is not ideal*. 

Perhaps it would be simplest to add a key point like "Authors often indicate how their content is available for reuse in a file called LICENSE or LICENSE.txt in the base directory of their repository", since that is already covered in the lesson. I still feel that this point should be reflected on the [Reference page](https://swcarpentry.github.io/git-novice/reference.html), but I also understand if it's not the consensus opinion :-)

**Comment by kekoziar** [comment]
@willblev, I like your proposed simplest key point.  Will you update your PR to reflect it?

**Comment by willblev** [comment]
@kekoziar Done!
