### ISSUE TITLE
Suggestion for modify image play-changes.svg

### ISSUE THREAD

**Issue by joenio** [swcarpentry/git-novice#883]
The image on 1st episode representing changes over a document could be changed a bit, see below some screenshots with the original image and the proposed modification.

original image:

![image](https://user-images.githubusercontent.com/44172/177040205-90a9a947-9d22-40c8-a304-86b3e06a5345.png)

highlight on the area I propose the modification:

![image](https://user-images.githubusercontent.com/44172/177040223-4473af4f-a4ff-4e22-bda1-31d92e037051.png)

modified image as proposed:

![image](https://user-images.githubusercontent.com/44172/177040244-df2017ea-28c6-4fbc-9d6c-8ce7e7510b60.png)

Maybe I understood wrong the idea behind this image but I think makes more sense modifying this image to reflect the proposition above.

**Comment by jrfep** [comment]
Thanks @joenio 
I think the original intended to show a modification of an existing line in the first step, and then adding three lines in the second step. Your proposal would show adding one line in the first step and then adding three lines in the second step. 
I like the original because it shows two different types of changes, but it does not make clear enough that the black line is deleted and replaced by the orange dashed line. 
Do you think you could add that idea of modifying a line to your proposal? or do you see another way to improve the original?

**Comment by joenio** [comment]
Thanks for your explanations @jrfep 

I see your point but I wonder if in the 1st episode (Automated Version Control) where we are teaching the very basic initial ideas about tracking modifications we really want to mix those 2 types of actions: adding lines and modifying lines.

My proposition is to simplify the example to keep only 1 kind of modification (doesn't matter if adding or modifying), I believe that in this step simplification is good.

Maybe the same image as it is now including examples of both type of actions (adding and modifying) lines can be added on some episode later (episode 04 "Tracking Changes" maybe?) and then there the image and also the textual content can explains in details that GIT tracks new lines added and also old lines modified as well, etc.

**Comment by kekoziar** [comment]
@joenio The situation described is motivation for the lesson.  It gives an overview of a common situation  - trying to keep track of and merge changes made by multiple people to a document - then explains at a high level that version control will help keep track of these types of changes and merge files.
