### ISSUE TITLE
Lesson Contribution: Add git stash to lesson plan

### ISSUE THREAD

**Issue by hunter-powell** [swcarpentry/git-novice#893]
I think adding a section on how to properly use git stash would be very beneficial to new git users. For people just getting started with coding and git it would be very useful to know how to save changes before pulling an updated version or when needing to revert to an older version for debugging purposes. All programmers run into issues and knowing how to stash current changes on git and add them back one at a time would be incredibly helpful in my opinion.

**Comment by benjwolff** [comment]
You are right: Knowing how to properly use git stash is very beneficial. From my perspective and experience, I would not teach git stash in the git-novice course. This course should cover the fundamentals and focus on the standard workflow (change, add, commit). Introducing things like git stash could be the next step in an intermediate course. Since git stash can be dangerous and lead to a loss of data, I wouldn't recommend to reach it in the git-novice course.

**Comment by martinosorb** [comment]
I agree that git stash should not be taught at the beginner level. Even at a more advanced level, I would prioritize branches and merging. Thanks for the suggestion.
