### ISSUE TITLE
Git novice - suggest replacing SSH access with personal access token

### ISSUE THREAD

**Issue by genghisken** [swcarpentry/git-novice#908]
Hi all - I see this issue has also been raised in #857 and #895, but I wanted to underline it here, having just helped with delivering the git-novice course (early December 2022).

Many of the trainees on the git-novice course have only just been introduced to bash, etc and git is already a fairly big jump for them. Additionally, they may have just been given remote SSH access to other services, and using SSH keys here introduces the real danger of them accidentally overwriting their other systems access keys.  Many of the trainees I was working with were bamboozled by the whole SSH key generation process, and I think it's a real distraction from the actual git syllabus.

May I suggest that you consider using personal access tokens (via HTTPS) rather than SSH.  I think the learning curve is much gentler. They can always do the SSH process in another course - or there could be an optional section here.

**Comment by kekoziar** [comment]
@genghisken thank you for the feedback. There have been long discussions regarding SSH vs PAT.  The end result is the git lesson inherited it because the Unix Shell maintainers suggested the best example for using it is git.  We did decide to [include more rather than less](https://github.com/swcarpentry/git-novice/issues/778#issuecomment-877677393), so an instructor can determine what they have time to go over.  And, many people agreed that SSH is better than PATs, because SSH is used more widely (and often in command line situations, not just for git).

There is a supplemental SSH episode still in development which includes PATs.  Please feel free to contribute.  Issue #824 describes how to contribute.

**Comment by kekoziar** [comment]
Closing as duplicate.
