### ISSUE TITLE
Version Control with Git: Tracking Changes.  Where did planets/moons go?

### ISSUE THREAD

**Issue by phwtsang** [swcarpentry/git-novice#919]
Per instructions in the episode, I created a new file by executing "nano mars.txt" and then "ls".  I saw the sub-directory moons which was created in the previous episode.  But the Output in the instruction did not show the sub-directory moons.  Should we instruct students to delete sub-directory moons before advancing to the second episode?

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

---

**Comment by kekoziar** [comment]
Thanks for the comment.  Challenge exercises are created to supplement episodes as formative assessment, and not necessarily extend content in the main lesson.  While exercises are listed at the end of the episode, each instructor may identify which exercise(s) they want to use during their workshop and when.  Depending on placement of the exercises, output may be different.  Since we can't include all possible variations of lesson and challenge exercises, we chose to only output content of the lesson in the lesson body.  I hope this provides clarity.
