### ISSUE TITLE
Pull in setup instructions as a submodule

### ISSUE THREAD

**Issue by bkmgit** [swcarpentry/git-novice#936]
The setup instructions are also used in the Shell novice lesson.  Referring to the workshop template is a little confusing.  Would you consider using a git submodule to allow them to be within the main lesson?

**Comment by zkamvar** [comment]
IMO, this is not a good solution because working with submodules is difficult even for people who are comfortable with Git. The problem arises because submodules by default will point to a single commit in the repository, but in a case like this, the lesson maintainers would much prefer to have them point to the HEAD of the repository, which is not straightforward (source: I've had to do this very thing for the lesson transition and it can be frustrating).

**Comment by zkamvar** [comment]
There has been discussion in the past about this, but not much capacity to address it, I'm afraid: https://github.com/carpentries/maintainer-RFCs/issues/9

**Comment by kekoziar** [comment]
I'm closing this issue as it's out of scope for the lesson.
