### ISSUE TITLE
About git init

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/git-novice#99]
Related with #98.

What about replace

~~~
$ mkdir new-repo
$ cd new-repo
$ git init
~~~

with

~~~
$ git init new-repo
$ cd new-repo
~~~

**Comment by drj11** [comment]
I never knew that `git init` could be used to create the directory. It does seem tidier.

**Comment by iglpdc** [comment]
I agree it's tidier, but I'm not convinced of the change. The reason is that I want to stress that the creation of the directory and the creation of the repo are two different and independent processes. Novice learners don't have a clear picture of what the repo is, so they think that this directory is special in some way, different from a regular directory. Having two separate commands for that, stresses this point.

When I teach this, I create the new directory, show it around stressing that this is the same as any other, and that this is probably something they already had in their computer (say the thesis you are working on for months and you decided now to put under version control).

Also, instead of writing the command to create the dir, I just tell them to do it: "let's create a new directory in our Desktop, using the commands we've seen in the shell lesson", so they review the `mkdir`, `cd` and `pwd`. As this takes some time, I have also the chance to be sure that everyone is creating the repo in the right place.

**Comment by r-gaia-cs** [comment]
@iglpdc Thanks for the comment. It makes sense to me and I'm closing this based on it. =)
